comment:
  behavior: default
  layout: diff
  require_changes: true
coverage:
  precision: 2
  range:
  - 60.0
  - 100.0
  round: down
  status:
    patch:
      default:
        threshold: 1%
    project:
      default:
        threshold: 1%
github_checks: false
